
class TradingSignals:
    """TradingSignals are generated by Strategies. They include all relevant
    trading calls and methods concerning their use. """
    def __init__(self):
        self.buy_signals = []
        self.sell_signals = []

    def __str__(self):
        pass

    def get_buy_signals(self):
        return self.buy_signals

    def get_sell_signals(self):
        return self.sell_signals
